<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup><EnableDynamicLoading>true</EnableDynamicLoading><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OpenD2.Core/OpenD2.Core.csproj" />
    <ProjectReference Include="../OpenD2.Assets/OpenD2.Assets.csproj" />
    <ProjectReference Include="../OpenD2.Npc/OpenD2.Npc.csproj" />
  </ItemGroup>
</Project>
